### ISSUE TITLE
failed to open file "/app/data/server.json", permission denied (error 13)

### ISSUE THREAD

**Issue by roldengarm** [firefrei/docker-snapcast#18]
Great stuff on making a Docker container for this! Unfortunately, with the default docker-compose.yml I get below error regarding app/data permissions.
I've also tried deleting all volumes in the docker-compose, but it still doesn't work.
```
snapserver-1  | 2025-04-17 06:57:03,731 INFO success: dbus entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
snapserver-1  | 2025-04-17 06:57:03,732 INFO success: avahi entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
snapserver-1  | 2025-04-17 06:57:03,732 INFO success: snapserver entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
snapserver-1  | 2025-04-17 06-57-03.733 [Error] (Snapserver) Exception: failed to open file "/app/data/server.json", permission denied (error 13)
```
docker-compose.yml
```
version: '3'

services:
  snapserver:
    image: 'ghcr.io/firefrei/snapcast/server:latest'
    restart: always
    #cap_add:
      #- NET_BIND_SERVICE   # Optional: allow container to bind privileged ports (>1024)
    environment:
      # See README.md for all environment options.
      TZ: Etc/UTC
      NGINX_ENABLED: "1"  # enable NGINX for HTTPS -> requires to bind to port 443 by default
      SPOTIFY_CONFIG_ENABLED: "1"
      #NGINX_HTTPS_PORT: "4433"  # use port 4433 instead of 4433
    volumes:
      # Snapcast: Configuration and run-time data
      - snapcast-data:/app/data/

    # Network Alternative 2: Use port-forwarding of host ports
    ports:
      # Snapcast Ports
      - '1704-1705:1704-1705'
      - '1780:1780'

      # Avahi ports
      - '5353:5353'
      # NGINX ports
#      - '443:443'
volumes:
  snapcast-data:
```
It must be something stupid, but I don't know why it doesn't work.
